# Site settings
title: Highly Clickable
email: christopherazar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a clever game of clicking
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://highlyclickable.com/" # the base hostname & protocol for your site
twitter_username: reptarazar
github_username:  reptarazar

# Build settings
markdown: kramdown
